export const SET_NET_INFO = 'global/SET_NET_INFO';
export const SET_SHOW_INTERNET_CONNECTION_MODAL = 'global/SET_SHOW_INTERNET_CONNECTION_MODAL';
export const SET_FAILED_API_REQUEST = 'global/SET_FAILED_API_REQUEST';