export const LEARNING_LOADING = "learning/LEARNING_LOADING";
export const GET_CHILDREN_LEARNING = "learning/GET_CHILDREN_LEARNING";
export const SET_CHILDREN_LEARNING = "learning/SET_CHILDREN_LEARNING";
export const CHILDREN_LEARNINGIMAGE_BS64 = "learning/CHILDREN_LEARNINGIMAGE_BS64";
