const childData = [
  {
    childImage: require('../assets/women.jpg'),
    childName: 'Abby',
    careEvents: [
      {
        id: 0,
        careType: 'Nappy',
        careDescription: 'Lorem ipsum dolor sit ametLorem ipsum dolor sit ametLorem ipsum dolor sit amet',
        eventTime: '1:25pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 1,
        careType: 'Food',
        careDescription: 'Ut enim ad minim veniam',
        eventTime: '12:00pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 2,
        careType: 'Sleep',
        careDescription: 'Sed quia consequuntur magni',
        eventTime: '11:15am',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 3,
        careType: 'Nappy',
        careDescription: 'Lorem ipsum dolor sit amet',
        eventTime: '1:25pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 4,
        careType: 'Food',
        careDescription: 'Ut enim ad minim veniam',
        eventTime: '12:00pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 5,
        careType: 'Sleep',
        careDescription: 'Sed quia consequuntur magni',
        eventTime: '11:15am',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 6,
        careType: 'Nappy',
        careDescription: 'Lorem ipsum dolor sit amet',
        eventTime: '1:25pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 7,
        careType: 'Food',
        careDescription: 'Ut enim ad minim veniam',
        eventTime: '12:00pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 8,
        careType: 'Sleep',
        careDescription: 'Sed quia consequuntur magni',
        eventTime: '11:15am',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
    ],
  },
  {
    childImage: null,
    childName: 'Bella',
    careEvents: [
      {
        id: 0,
        careType: 'Sleep',
        careDescription: 'Lorem ipsum dolor sit amet',
        eventTime: '1:25pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 1,
        careType: 'Food',
        careDescription: 'Ut enim ad minim veniam',
        eventTime: '12:00pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 2,
        careType: 'Food',
        careDescription: 'Sed quia consequuntur magni',
        eventTime: '11:15am',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 3,
        careType: 'Nappy',
        careDescription: 'Lorem ipsum dolor sit amet',
        eventTime: '1:25pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 4,
        careType: 'Nappy',
        careDescription: 'Ut enim ad minim veniam',
        eventTime: '12:00pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 5,
        careType: 'Sleep',
        careDescription: 'Sed quia consequuntur magni',
        eventTime: '11:15am',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 6,
        careType: 'Sleep',
        careDescription: 'Lorem ipsum dolor sit amet',
        eventTime: '1:25pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 7,
        careType: 'Food',
        careDescription: 'Ut enim ad minim veniam',
        eventTime: '12:00pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 8,
        careType: 'Nappy',
        careDescription: 'Sed quia consequuntur magni',
        eventTime: '11:15am',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },    
    ],
  },
  {
    childImage: require('../assets/smiling.jpg'),
    childName: 'Christine',
    careEvents: [
      {
        id: 0,
        careType: 'Sleep',
        careDescription: 'Lorem ipsum dolor sit amet',
        eventTime: '1:25pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 1,
        careType: 'Sleep',
        careDescription: 'Ut enim ad minim veniam',
        eventTime: '12:00pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 2,
        careType: 'Sleep',
        careDescription: 'Sed quia consequuntur magni',
        eventTime: '11:15am',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 3,
        careType: 'Nappy',
        careDescription: 'Lorem ipsum dolor sit amet',
        eventTime: '1:25pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 4,
        careType: 'Food',
        careDescription: 'Ut enim ad minim veniam',
        eventTime: '12:00pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 5,
        careType: 'Sleep',
        careDescription: 'Sed quia consequuntur magni',
        eventTime: '11:15am',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 6,
        careType: 'Nappy',
        careDescription: 'Lorem ipsum dolor sit amet',
        eventTime: '1:25pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 7,
        careType: 'Food',
        careDescription: 'Ut enim ad minim veniam',
        eventTime: '12:00pm',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
      {
        id: 8,
        careType: 'Sleep',
        careDescription: 'Sed quia consequuntur magni',
        eventTime: '11:15am',
        careInfo: {staffName: "David", staffComments: "Had a rash so applied cream"},
      },
    ],
  },
  {
    childImage: null,
    childName: "Empty",
    careEvents: [],
  },
];

export default childData;