export const DAILY_CARE_LOADING = "dailyCare/DAILY_CARE_LOADING";
export const GET_ACTIVITY_BY_LAST_MODIFIED_DATE =
  "dailyCare/GET_ACTIVITY_BY_LAST_MODIFIED_DATE";
export const SET_ACTIVITY_BY_LAST_MODIFIED_DATE =
  "dailyCare/SET_ACTIVITY_BY_LAST_MODIFIED_DATE";
export const GET_ACTIVITY_BY_RANGE_DATE =
  "dailyCare/GET_ACTIVITY_BY_RANGE_DATE";
export const SET_ACTIVITY_BY_RANGE_DATE =
  "dailyCare/SET_ACTIVITY_BY_RANGE_DATE";
export const GET_CHILDREN_TIMELINE = "dailyCare/GET_CHILDREN_TIMELINE";
export const SET_CHILDREN_TIMELINE = "dailyCare/SET_CHILDREN_TIMELINE";
export const GET_LOOKUP = "dailyCare/GET_LOOKUP";
export const SET_LOOKUP = "dailyCare/SET_LOOKUP";
