export const CHANGE_PASSWORD_REQUEST = "profile/CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD = "profile/CHANGE_PASSWORD";
export const CHANGE_PASSWORD_COMPLETED = "profile/CHANGE_PASSWORD_COMPLETED";